### ISSUE TITLE
GEOIp locations

### ISSUE THREAD

**Issue by Geronimo2015** [agabani/tor-operator#294]
When I specify ExitNodes I get an error on missing GEOIp files.

```
  torrc:
    template: |
      ExitNodes {us}
      StrictNodes 1
```

```
Jan 06 14:51:19.000 [warn] Failed to open GEOIP file /tor-0.4.8.13/install/share/tor/geoip.
Jan 06 14:51:19.000 [warn] We've been configured to use (or avoid) nodes in certain countries, and we need GEOIP information to figure out which ones they are.
Jan 06 14:51:19.000 [warn] Failed to open GEOIP file /tor-0.4.8.13/install/share/tor/geoip6.
Jan 06 14:51:19.000 [warn] We've been configured to use (or avoid) nodes in certain countries, and we need GEOIP information to figure out which ones they are.
```

Can those be included in the Docker image?

**Comment by Geronimo2015** [comment]
I worked around it by downloading and mounting the required files during init containers.

**Comment by agabani** [comment]
To future explorers,

I'm against adding GeoIP to `ghcr.io/agabani/tor-operator:tor-*` because the MaxMind has some clauses regarding redistribution of their databases.

You can extend the installation to suit your needs using a few methods.

---

Method 1. extend at runtime using:

- https://agabani.github.io/tor-operator/docs/custom_resource_definitions/toringress/#containers
- https://agabani.github.io/tor-operator/docs/custom_resource_definitions/torproxy/#containers

non-accurate example:
```yaml
apiVersion: tor.agabani.co.uk/v1
kind: TorIngress / TorProxy
spec:
  # ...
  deployment:
    containers:
      - name: tor
        volumeMounts:
          - name: geoip
            mountPath: /some/path
            # ...
      - name: geoip-updater
        args:
          - -c
          - # ....
        command:
          - /bin/bash 
        volumeMounts:
          - name: geoip
            mountPath: /some/path
            # ...
    initContainers:
      - name: geoip-downloader
        args:
          - -c
          - # ....
        command:
          - /bin/bash
        volumeMounts:
          - name: geoip
            mountPath: /some/path
            # ...
    volumes:
      - name: geoip
        emptyDir:
          sizeLimit: 32Mi
  torrc:
    template: |
      GeoIPFile /some/path/filename
```

---

Method 2. extend at install time:

1. create and push your own `tor` container image:

    ```Dockerfile
    FROM ghcr.io/agabani/tor-operator:tor-*
    
    COPY ./some/path/filename /some/path/filename
    ```



2. Configure `tor-operator` to use your own `tor` container image:

    ```shell
    # https://github.com/agabani/tor-operator/blob/v0.0.33/charts/tor-operator/values.yaml#L21-L23
    helm upgrade tor-operator agabani-tor-operator/tor-operator \
        --create-namespace \
        --install \
        --namespace tor-operator \
	    --set tor.image.repository=your-repository-goes-here \
	    --set tor.image.tag=your-tag-goes-here
    ```
