### ISSUE TITLE
[Feature Request] Integrate IPinfo's free IP to Country Database

### ISSUE THREAD

**Issue by abdullahdevrel** [agabani/tor-operator#295]
I am requesting to add support for [IPinfo's IP to Country database](https://ipinfo.io/products/free-ip-database) to the project. The database has the following features:

- It is updated daily, with zero compromise to accuracy. There is no range clustering, and the database provides full accuracy.
- The data granularity reaches individual IP level.
- The database comes in MMDB database format.
- It is licensed under CC-BY-SA 4.0, permitting commercial usage.
- Available file formats include: CSV, MMDB, JSON
- The data is tabular and unnested, making it very easy to use. The dataset includes both IPv4 and IPv6 in a single file.

## Database schema

| Field Name       | Example                      | Data Type | Description                                       |
|------------------|------------------------------|-----------|---------------------------------------------------|
| `start_ip`       | 1.0.16.0                     | TEXT      | Starting IP address of an IP address range        |
| `end_ip`         | 1.0.31.255                   | TEXT      | Ending IP address of an IP address range          |
| `country`        | JP                           | TEXT      | ISO 3166 country code of the location             |
| `country_name`   | Japan                        | TEXT      | Name of the country                               |
| `continent`      | AS                           | TEXT      | Continent code of the country                     |
| `continent_name` | Asia                         | TEXT      | Name of the continent                             |

Documentation: https://ipinfo.io/developers/ip-to-country-database

Samples are available here: https://github.com/ipinfo/sample-database/tree/main/IP%20to%20Country

The database can be downloaded simply by accessing the [storage URI with an access token](https://ipinfo.io/developers/database-filename-reference).

```bash
curl -L https://ipinfo.io/data/free/country.mmdb?token=<YOUR_TOKEN> -o country.mmdb
```

Let me know what you think. Thanks!

**Comment by agabani** [comment]
Tor Operator is a Kubernetes Operator for automated management of Tor. This feature request is outside the remits of Tor Operator because it targets the Tor distribution.

A minimal Tor distribution has been provided as a convenience for friction-free developer and end-user experience. When the minimal Tor distribution no longer fulfills the end-user's requirements, the end-user may extend their implementation by either:

- using their own Tor distribution, example:

  ```shell
  helm upgrade tor-operator agabani-tor-operator/tor-operator \
      --create-namespace \
      --install \
      --namespace tor-operator \
      --set tor.image.repository=your-repository-goes-here \
      --set tor.image.tag=your-tag-goes-here
  ```

- modifying the minimal Tor distribution at runtime, example:

  ```yaml
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: onion-service-{{ include "example.fullname" . }}-geoip-token
    labels:
      {{- include "example.labels" . | nindent 4 }}
  data:
    token: MDEyMzQ1Njc4OWFiY2RlZg==
  
  ---
  apiVersion: tor.agabani.co.uk/v1
  kind: OnionKey
  metadata:
    name: onion-service-{{ include "example.fullname" . }}-geoip
    labels:
      {{- include "example.labels" . | nindent 4 }}
  spec:
    autoGenerate: true
    secret:
      name: onion-service-{{ include "example.fullname" . }}-geoip
  
  ---
  apiVersion: tor.agabani.co.uk/v1
  kind: OnionService
  metadata:
    name: onion-service-{{ include "example.fullname" . }}-geoip
    labels:
      {{- include "example.labels" . | nindent 4 }}
  spec:
    deployment:
      containers:
        - name: tor
          volumeMounts:
            - name: tmp-shared
              mountPath: /tmp/shared
      initContainers:
        - name: geoip-download
          args:
            - -c 
            - curl --fail -L https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN} -o /tmp/shared/country.mmdb
          command:
            - /bin/sh
          env:
            - name: IPINFO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onion-service-{{ include "example.fullname" . }}-geoip-token
                  key: token
          image: curlimages/curl:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tmp-shared
              mountPath: /tmp/shared
      volumes:
        - name: tmp-shared
          emptyDir:
            sizeLimit: 128Mi
    onionKey:
      name: onion-service-{{ include "example.fullname" . }}-geoip
    ports:
      - target: example:80
        virtport: 80
    torrc:
      template: |
        GeoIPFile /tmp/shared/country.mmdb
        ExitNodes {GB}
        StrictNodes 1
  ```
